version: '3'
services:
  nginx:
    image: lexcorp/nginx
    container_name: nginx
    networks:
      - lexnet
    ports:
      - "8080:80"
    depends_on:
      - app
  app:
    image: lexcorp/node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s docker-entrypoint.sh
    command: node index.js
    networks:
      - lexnet
    tty: true
    depends_on:
       - db
  db:
    image: lexcorp/mysql
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - lexnet
networks:
  lexnet:
    driver: bridge